### ISSUE TITLE
Can't open database

### ISSUE THREAD

**Issue by MarianoGnu** [khairul169/gdsqlite-native#6]
When i try to open a DB from a tool script i get this error on the console:
Nonexistant method "open_database"

![imagen](https://user-images.githubusercontent.com/1776044/37256599-d091dc08-253b-11e8-993b-1d314e9bb326.png)

**Comment by MarianoGnu** [comment]
Opened an issue on Godot, since i'm not sure if this is because of this plugin or because GdNative itself
https://github.com/godotengine/godot/issues/17613

**Comment by MarianoGnu** [comment]
@khairul169 someone pointed out that current implementation has function that has been removed from NativeScript

https://github.com/godotengine/godot/issues/17613#issuecomment-374035743

**Comment by 8ace40** [comment]
Latest version this works is 3.0 beta 1, if anyone wants to try this tool but can't make it work. [Here](https://downloads.tuxfamily.org/godotengine/3.0-old/beta1/) is a link for convenience.

**Comment by MarianoGnu** [comment]
maybe sqlite release 1 is not the lastest commit and this is fixed on master? i cant compile it (don't know what's the problem with my pc, it says i have not a compiler installed)

**Comment by 8ace40** [comment]
Nope, it's not fixed. [/src/gdsqlite.c](https://github.com/khairul169/gdsqlite-native/blob/master/src/gdsqlite.c) still has the old functions.
I also tried to recompile but something changed in the latest version of cpp_bindings and it' way above my knowledge to fix.
I'm sorry I can't be of more help.

**Comment by khairul169** [comment]
Thanks for the information!
Yeah, this module is outdated and need to be updated with the latest
version of godot.. I'll fix this when i am available..

This module doesn't need cpp binding BTW.. It only need gdnative c headers..

**Comment by khairul169** [comment]
SQLite module that is working with latest godot engine has been pushed to the master branch.

About the tool script, i don't know what happened.. It seems that the module are not loaded when running in the editor with "tool" keyword..

```
==========================
_init()
[SQLite] Module loaded.
SCRIPT ERROR: _init: Invalid call. Nonexistent function 'open_database' in base 'Reference (sqlite.gdns)'.
          At: res://scene.gd:22
Running: E:\Software\Godot_v3.0-stable_mono_win64\Godot_v3.0.2-stable_win64.exe --path D:/Projects/gdsqlite-native/godot_project --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 2440 --position 171,84
running cmdline: "E:\Software\Godot_v3.0-stable_mono_win64\Godot_v3.0.2-stable_win64.exe" "--path" "D:/Projects/gdsqlite-native/godot_project" "--remote-debug" "127.0.0.1:6007" "--allow_focus_steal_pid" "2440" "--position" "171,84"
OpenGL ES 3.0 Renderer: GeForce 820M/PCIe/SSE2
> register_method("open_database");
> register_method("query");
> register_method("fetch_array");
> nativescript_init();
==========================
_init()
[SQLite] Module loaded.
[SQLite] Database path: user://test.sql
(email:user@test.org), (first_name:godot), (id:1), (last_name:engine)
```

**Comment by MarianoGnu** [comment]
Great, will give it a try, i'll probably need to open an issue on godot to allow native scripts to run on editor

I'll have to fix my build toolchain this weekend, i cant stand not being able to ocmpile anything -_-
